### PR TITLE
Unify poms

### PR DESCRIPTION
**Pull request by ctrueden**
__[THIS IS A DISCUSSION PR, NOT YET READY TO MERGE]__

Hi @StephanPreibisch, @RichardMyers, @sbesson, et. al,

I am trying to bring this component back into sync with the latest Fiji distribution. Fiji now ships a version of Bio-Formats that no longer includes the SlideBook6Reader (see openmicroscopy/bioformats#2496 for details).

I have updated things to use the latest `org.scijava:pom-scijava:13.0.0`, but there are compile errors relating to this component's direct usage of `SlideBook6Reader`, which no longer exists.

What is the correct way forward here to reconcile things?

Note that as things stand, I would be shocked if this component's SlideBook6 logic was actually working in an up-to-date version of Fiji.

### CODE REVIEW

**Comment by StephanPreibisch** [comment]
Hi @ctrueden, I just talked to @RichardMyers and he will try to implement the SlideBook6ImgLoader just using the Bioformats API instead of calling the SlideBook6Reader directly, the same way the LightsheetZ1ImgLoader is implemented. That will solve the problem, right? We can talk more about it in Lisbon too, maybe it is fixed until then. Thanks a lot, Stephan

**Comment by ctrueden** [comment]
@RichardMyers Any news?

@StephanPreibisch Are you here in Lisbon? I would really like to get this resolved. We need to update this component to the latest Bio-Formats so that it keeps working in Fiji.

**Comment by RichardMyers** [comment]
@ctrueden I'm working to factor out the direct dependency and use the bio-formats abstract interface for loading SlideBook data.  I'm on vacation next week so it might not be until March that I have something ready.

**Comment by StephanPreibisch** [comment]
Hi, I'll be in Lisbon tomorrow evening, let's figure it out then! Thanks a lot and see you soon Curtis!

**Comment by RichardMyers** [comment]
FYI, I've made the changes to the SlideBook6 image loader classes to factor out direct calls to the SlideBook6Reader bio-formats plugin and to use the abstract bio-formats image loader interface instead.

I'd like to do some more testing before I submit the pull request.  So far it looks like it will work well though.

**Comment by RichardMyers** [comment]
@ctrueden @StephanPreibisch I've created PR #118 which should solve the problem of direct access to native libraries and use abstract bio-formats interface.  Sorry for the delay, but should be all good now.

**Comment by ctrueden** [comment]
@RichardMyers Thank you so much! With your changes, I was able to cleanly complete this work. So hopefully, all of the SlideBook goodies will work again in up-to-date Fiji installations, just as soon as we cut releases and upload them.

**Comment by RichardMyers** [comment]
@ctrueden Sorry for not doing it right the first time and glad we're not blocking progress anymore.   Thank you for all of your hard work!

**Pull request merged**
