### PR TITLE
Fixes to SlideBook SLD file reader

### PR DESCRIPTION
**Pull request by RichardMyers**
Fixed SlideBook SLD file image,channel,angle naming to make it work with scripts; also fixed reading multichannel sld files

### CODE REVIEW

**Comment by ctrueden** [comment]
It concerns me to see all this effort being done on another SLD reader that is not the Bio-Formats reader, and is not SCIFIO-based. What is the long term plan here?

**Comment by RichardMyers** [comment]
This plugin has custom readers for a handful of file formats (eg. LightSheet Z1), but there does not appear to be a way to generically read all file formats supported by Bio-Formats.   We would certainly prefer to use a more generic Bio-Formats based system if one existed.

**Comment by ctrueden** [comment]
> there does not appear to be a way to generically read all file formats supported by Bio-Formats. We would certainly prefer to use a more generic Bio-Formats based system if one existed.

You certainly can read data agnostically using the Bio-Formats API, via the `loci.formats.ImageReader` class. There is [lots of documentation](https://www.openmicroscopy.org/site/support/bio-formats5.3/developers/file-reader.html).

I know that @StephanPreibisch is familiar with this API, having used it in the past.

If there is something I'm missing here, please let me know.

**Comment by RichardMyers** [comment]
@ctrueden When I began this project with @StephanPreibisch the bio-formats project was planned to include SlideBook6Reader directly. Later, as you mentioned in [fiji/SPIM_Registration/pull/115](https://github.com/fiji/SPIM_Registration/pull/115), it was decided that the SlideBook6Reader should be moved to be an external project that is late loaded, as per [openmicroscopy/bioformats/pull/2496](https://github.com/openmicroscopy/bioformats/pull/2496).

As you suggest above, the correct way forward is to make the required changes to the SPIM_Registration plugin to load SlideBook6 files using the loci.formats.ImageReader infrastructure, similar to how the LightSheetZ1 reader operates. 

I am not as experienced with Java or the Bioformats/ImageJ universe of inter-related technologies as I should be, which is why I went with the simpler direct method originally.  I'll give it a try, but I appreciate your understanding that this is a non-trivial change for me to make.

**Comment by StephanPreibisch** [comment]
Hi @RichardMyers @ctrueden, I think Curtis and me should discuss the long-term strategy at the NEUBIAS meeting in Lisbon. I will merge this request for now to move forward. Thanks a lot, Stephan

**Pull request merged**
