### PR TITLE
Checked compat with JNA 5.11.0

### PR DESCRIPTION
**Pull request by mkitti**
Update scijava-pom to 31.1.0
Checked compat with JNA 5.11.0
Use Native.load rather than Native.loadLibrary

xref: https://github.com/scijava/pom-scijava/issues/163

### CODE REVIEW

**Comment by ctrueden** [comment]
@mkitti Uh oh, I just noticed this. Now that we've upgraded Fiji to JNA 5.11.0, but not merged this PR... are there problems with SPIM_Registration? Shall we rebase/update this PR and get it merged?

**Comment by mkitti** [comment]
Native.loadLibrary is deprecated and should be changed to Native.load.

**Comment by ctrueden** [comment]
> Native.loadLibrary is deprecated and should be changed to Native.load.

@mkitti Noted. But it's just deprecation, not actual breakage, right? 

In any case, I rebased the PR, fixed the conflicts, and merged this. Let me know if an immediate release is needed or not.

**Comment by mkitti** [comment]
I do not think an immediate release is needed.

https://java-native-access.github.io/jna/5.5.0/javadoc/com/sun/jna/Native.html#loadLibrary-java.lang.Class-

**Pull request merged**
